export interface GoogleFont {
  family: string;
  category: "sans-serif" | "serif" | "display" | "handwriting" | "monospace";
}

export const GOOGLE_FONTS: GoogleFont[] = [
  // Sans Serif
  { family: "Inter", category: "sans-serif" },
  { family: "Roboto", category: "sans-serif" },
  { family: "Open Sans", category: "sans-serif" },
  { family: "Lato", category: "sans-serif" },
  { family: "Montserrat", category: "sans-serif" },
  { family: "Poppins", category: "sans-serif" },
  { family: "Nunito", category: "sans-serif" },
  { family: "Raleway", category: "sans-serif" },
  { family: "Ubuntu", category: "sans-serif" },
  { family: "Work Sans", category: "sans-serif" },
  { family: "Rubik", category: "sans-serif" },
  { family: "Manrope", category: "sans-serif" },
  { family: "DM Sans", category: "sans-serif" },
  { family: "Space Grotesk", category: "sans-serif" },
  { family: "Plus Jakarta Sans", category: "sans-serif" },
  { family: "Outfit", category: "sans-serif" },
  { family: "Figtree", category: "sans-serif" },
  { family: "Source Sans 3", category: "sans-serif" },
  { family: "Noto Sans", category: "sans-serif" },
  { family: "Lexend", category: "sans-serif" },
  { family: "Albert Sans", category: "sans-serif" },
  { family: "Sora", category: "sans-serif" },
  { family: "Karla", category: "sans-serif" },
  { family: "Josefin Sans", category: "sans-serif" },
  { family: "Quicksand", category: "sans-serif" },
  { family: "Barlow", category: "sans-serif" },
  { family: "Mulish", category: "sans-serif" },
  { family: "Cabin", category: "sans-serif" },
  { family: "Overpass", category: "sans-serif" },
  { family: "Archivo", category: "sans-serif" },

  // Serif
  { family: "Playfair Display", category: "serif" },
  { family: "Lora", category: "serif" },
  { family: "Merriweather", category: "serif" },
  { family: "PT Serif", category: "serif" },
  { family: "Libre Baskerville", category: "serif" },
  { family: "Noto Serif", category: "serif" },
  { family: "EB Garamond", category: "serif" },
  { family: "Crimson Text", category: "serif" },
  { family: "Cormorant Garamond", category: "serif" },
  { family: "Source Serif 4", category: "serif" },
  { family: "DM Serif Display", category: "serif" },
  { family: "Bitter", category: "serif" },
  { family: "Spectral", category: "serif" },
  { family: "Frank Ruhl Libre", category: "serif" },
  { family: "Vollkorn", category: "serif" },
  { family: "Cardo", category: "serif" },
  { family: "Alegreya", category: "serif" },
  { family: "Fraunces", category: "serif" },
  { family: "Old Standard TT", category: "serif" },
  { family: "Bodoni Moda", category: "serif" },

  // Display
  { family: "Bebas Neue", category: "display" },
  { family: "Righteous", category: "display" },
  { family: "Bungee", category: "display" },
  { family: "Abril Fatface", category: "display" },
  { family: "Alfa Slab One", category: "display" },
  { family: "Anton", category: "display" },
  { family: "Lobster", category: "display" },
  { family: "Passion One", category: "display" },
  { family: "Fredoka One", category: "display" },
  { family: "Bangers", category: "display" },
  { family: "Lilita One", category: "display" },
  { family: "Russo One", category: "display" },
  { family: "Press Start 2P", category: "display" },
  { family: "Bungee Shade", category: "display" },
  { family: "Monoton", category: "display" },
  { family: "Black Ops One", category: "display" },
  { family: "Dela Gothic One", category: "display" },
  { family: "Modak", category: "display" },
  { family: "Bowlby One SC", category: "display" },
  { family: "Bungee Inline", category: "display" },

  // Handwriting
  { family: "Dancing Script", category: "handwriting" },
  { family: "Pacifico", category: "handwriting" },
  { family: "Caveat", category: "handwriting" },
  { family: "Great Vibes", category: "handwriting" },
  { family: "Sacramento", category: "handwriting" },
  { family: "Satisfy", category: "handwriting" },
  { family: "Kaushan Script", category: "handwriting" },
  { family: "Indie Flower", category: "handwriting" },
  { family: "Patrick Hand", category: "handwriting" },
  { family: "Architects Daughter", category: "handwriting" },
  { family: "Shadows Into Light", category: "handwriting" },
  { family: "Permanent Marker", category: "handwriting" },
  { family: "Amatic SC", category: "handwriting" },
  { family: "Gloria Hallelujah", category: "handwriting" },
  { family: "Rock Salt", category: "handwriting" },
  { family: "Homemade Apple", category: "handwriting" },
  { family: "Zeyada", category: "handwriting" },
  { family: "Reenie Beanie", category: "handwriting" },
  { family: "Nothing You Could Do", category: "handwriting" },
  { family: "Sue Ellen Francisco", category: "handwriting" },

  // Monospace
  { family: "JetBrains Mono", category: "monospace" },
  { family: "Fira Code", category: "monospace" },
  { family: "Source Code Pro", category: "monospace" },
  { family: "IBM Plex Mono", category: "monospace" },
  { family: "Roboto Mono", category: "monospace" },
  { family: "Space Mono", category: "monospace" },
  { family: "Inconsolata", category: "monospace" },
  { family: "Ubuntu Mono", category: "monospace" },
  { family: "Courier Prime", category: "monospace" },
  { family: "DM Mono", category: "monospace" },
];

export const FONT_CATEGORIES = [
  { value: "all", label: "All" },
  { value: "sans-serif", label: "Sans Serif" },
  { value: "serif", label: "Serif" },
  { value: "display", label: "Display" },
  { value: "handwriting", label: "Handwriting" },
  { value: "monospace", label: "Mono" },
] as const;
